// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook';

import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // 從 .eslintignore 移植：MSW 產生的檔案
    'public/mockServiceWorker.js',
    // Generated by tsx generate-i18n-types.ts — 改規則沒用，只能 ignore
    '**/*.generated.ts',
    // Storybook build output（600+ 檔案 / 21MB），不 ignore 會卡 10+ 分鐘
    'storybook-static/**',
  ]),
  ...storybook.configs['flat/recommended'],
  {
    rules: {
      // 前端大量 any 用於 GraphQL fetch / Apollo cache / form payload，降為 warn
      '@typescript-eslint/no-explicit-any': 'warn',
      // React Compiler 嚴格優化檢查降為 warn（提示但不阻擋）
      'react-hooks/static-components': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/incompatible-library': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/immutability': 'warn',
    },
  },
  {
    // Storybook stories：允許描述性文字使用原生引號
    files: ['**/*.stories.tsx', '**/*.stories.ts'],
    rules: {
      'react/no-unescaped-entities': 'off',
    },
  },
  {
    // Playwright e2e fixtures 用 use() callback — 跟 React use() 同名，
    // 但 e2e 不是 React 元件，react-hooks 規則整個不適用
    files: ['e2e/**/*.ts', 'e2e/**/*.tsx'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/exhaustive-deps': 'off',
    },
  },
]);

export default eslintConfig;
