/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "emailAlreadyRegistered": string;
        "invalidCredentials": string;
        "userNotFound": string;
        "invalidTemporaryToken": string;
        "verificationFailed": string;
        "codeExpiredOrInvalid": string;
        "twoFactorCodeSent": string;
        "invalidResetToken": string;
        "passwordSameAsOld": string;
        "cannotDeleteSystemRole": string;
        "loginFailed": string;
    };
    "common": {
        "forbidden": {
            "noUserInfo": string;
            "requireScope": string;
            "requireAnyScope": string;
            "requirePermission": string;
            "requireAnyPermission": string;
            "requireAllPermissions": string;
        };
        "unknown": string;
    };
    "email": {
        "passwordReset": {
            "subject": string;
        };
        "passwordChanged": {
            "subject": string;
        };
        "profileUpdated": {
            "subject": string;
        };
        "twoFactorCode": {
            "login": string;
            "enable": string;
            "disable": string;
            "default": string;
        };
    };
    "twoFactor": {
        "alreadyEnabled": string;
        "notEnabled": string;
        "codeSent": string;
        "enableSuccess": string;
        "disableSuccess": string;
        "codeNotFoundOrExpired": string;
        "tooManyAttempts": string;
        "codeInvalid": string;
    };
    "validation": {
        "password": {
            "strengthFailed": string;
            "minLength": string;
            "uppercase": string;
            "lowercase": string;
            "number": string;
            "specialChar": string;
            "tooCommon": string;
            "similarToEmail": string;
            "similarToName": string;
            "similarToUsername": string;
            "currentIncorrect": string;
            "mustBeDifferent": string;
        };
        "email": {
            "invalid": string;
            "alreadyUsed": string;
        };
        "name": {
            "maxLength": string;
        };
        "website": {
            "invalid": string;
        };
        "language": {
            "invalid": string;
        };
        "user": {
            "notFound": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
