import { paletteBase } from './paletteBase';
import { tones } from './tones';

const grey = paletteBase.grey;
const white = tones.primary[0];

export const actionButtonTokens = {
  default: {
    size: 32,
    borderRadius: '50%',
    bg: tones.primary[50],
    hoverBg: tones.primary[100],
    pressedBg: tones.primary[200],
    icon: tones.primary[500],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  defaultPillSm: {
    height: 32,
    paddingX: 12,
    paddingY: 4,
    borderRadius: 20,
    bg: tones.primary[50],
    hoverBg: tones.primary[100],
    pressedBg: tones.primary[200],
    icon: tones.primary[500],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  defaultPill: {
    height: 40,
    paddingX: 12,
    paddingY: 4,
    borderRadius: 20,
    bg: tones.primary[50],
    hoverBg: tones.primary[100],
    pressedBg: tones.primary[200],
    icon: tones.primary[500],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  standard: {
    size: 32,
    borderRadius: '50%',
    bg: 'transparent',
    hoverBg: grey[50],
    pressedBg: grey[100],
    icon: grey[900],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  standardPillSm: {
    height: 32,
    paddingX: 12,
    paddingY: 4,
    borderRadius: 20,
    bg: 'transparent',
    hoverBg: grey[50],
    pressedBg: grey[100],
    icon: grey[900],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  standardPill: {
    height: 40,
    paddingX: 12,
    paddingY: 4,
    borderRadius: 20,
    bg: 'transparent',
    hoverBg: grey[50],
    pressedBg: grey[100],
    icon: grey[900],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  outline: {
    size: 32,
    borderRadius: '50%',
    border: grey[200],
    bg: white,
    hoverBg: grey[50],
    pressedBg: grey[100],
    icon: grey[900],
    disabledBorder: grey[200],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  outlinePillSm: {
    height: 32,
    paddingX: 12,
    paddingY: 4,
    borderRadius: 20,
    border: grey[200],
    bg: white,
    hoverBg: grey[50],
    pressedBg: grey[100],
    icon: grey[900],
    disabledBorder: grey[200],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
  outlinePill: {
    height: 40,
    paddingX: 12,
    paddingY: 4,
    borderRadius: 20,
    border: grey[200],
    bg: white,
    hoverBg: grey[50],
    pressedBg: grey[100],
    icon: grey[900],
    disabledBorder: grey[200],
    disabledBg: grey[50],
    disabledIcon: grey[300],
  },
} as const;
