import { paletteBase } from './paletteBase';
import { tones } from './tones';

const grey = paletteBase.grey;
const white = tones.primary[0];

export const buttonTokens = {
  contained: {
    borderRadius: 20,
    paddingX: 16,
    paddingY: 6,
    iconSpacing: 8,
    sizes: {
      small: { paddingX: 10, paddingY: 4 },
      medium: { paddingX: 16, paddingY: 6 },
      large: { paddingX: 22, paddingY: 8 },
    },
    bg: tones.primary[500],
    hoverBg: tones.primary[600],
    pressedBg: tones.primary[700],
    text: white,
    disabledBg: grey[50],
    disabledText: grey[300],
  },
  outlined: {
    borderRadius: 20,
    paddingX: 15,
    paddingY: 5,
    iconSpacing: 8,
    sizes: {
      small: { paddingX: 9, paddingY: 3 },
      medium: { paddingX: 15, paddingY: 5 },
      large: { paddingX: 21, paddingY: 7 },
    },
    border: grey[200],
    bg: white,
    hoverBg: grey[50],
    pressedBg: grey[100],
    text: grey[900],
    disabledBorder: grey[200],
    disabledText: grey[300],
  },
  text: {
    borderRadius: 20,
    paddingX: 8,
    paddingY: 6,
    iconSpacing: 8,
    sizes: {
      small: { paddingX: 5, paddingY: 4 },
      medium: { paddingX: 8, paddingY: 6 },
      large: { paddingX: 11, paddingY: 8 },
    },
    text: tones.primary[500],
    hoverBg: tones.primary[50],
    pressedBg: tones.primary[100],
    disabledText: grey[300],
  },
  elevated: {
    borderRadius: 6,
    paddingX: 16,
    paddingY: 6,
    iconSpacing: 8,
    sizes: {
      small: { paddingX: 10, paddingY: 4 },
      medium: { paddingX: 16, paddingY: 6 },
      large: { paddingX: 22, paddingY: 8 },
    },
    bg: `linear-gradient(180deg, ${tones.primary[400]} 0%, ${tones.primary[600]} 100%)`,
    hoverBg: tones.primary[400],
    pressedBg: tones.primary[600],
    text: white,
    disabledBg: grey[50],
    disabledText: grey[300],
    boxShadow:
      '0 2px 3px 0 rgba(255, 255, 255, 0.35) inset, 0 10px 30px 0 rgba(224, 50, 11, 0.40)',
  },
  tagContained: {
    borderRadius: 20,
    height: 28,
    paddingX: 12,
    paddingY: 4,
    iconSpacing: 6,
    bg: grey[50],
    hoverBg: grey[100],
    pressedBg: grey[200],
    text: grey[900],
    disabledBg: grey[50],
    disabledText: grey[300],
  },
  tagText: {
    borderRadius: 20,
    height: 28,
    paddingX: 12,
    paddingY: 4,
    iconSpacing: 6,
    text: tones.primary[500],
    hoverBg: tones.primary[50],
    pressedBg: tones.primary[100],
    disabledText: grey[300],
  },
  iconGradient: {
    borderRadius: '50px',
    paddingX: 16,
    paddingY: 6,
    iconSpacing: 8,
    sizes: {
      small: { paddingX: 10, paddingY: 4 },
      medium: { paddingX: 16, paddingY: 6 },
      large: { paddingX: 22, paddingY: 8 },
    },
    bg: `linear-gradient(180deg, ${white} 0%, ${tones.primary[50]} 100%)`,
    boxShadow: `0 2px 1px 0 ${tones.primary[100]}`,
    hoverBg: tones.primary[50],
    pressedBg: tones.primary[100],
    disabledBg: `linear-gradient(180deg, ${white} 0%, ${grey[100]} 100%)`,
    disableBoxShadow: `0 2px 1px 0 ${grey[200]}`,
    iconColor: tones.primary[500],
  },
} as const;
